version = 1

[[analyzers]]
name = "secrets"

[[analyzers]]
name = "rust"

  [analyzers.meta]
  msrv = "stable"

[[analyzers]]
name = "sql"

[[analyzers]]
name = "python"

  [analyzers.meta]
  runtime_version = "3.x.x"

[[analyzers]]
name = "php"

[[analyzers]]
name = "ansible"

[[analyzers]]
name = "shell"

[[analyzers]]
name = "ruby"

[[transformers]]
name = "rubocop"

[[transformers]]
name = "standardrb"

[[transformers]]
name = "black"

[[transformers]]
name = "isort"

[[transformers]]
name = "yapf"

[[transformers]]
name = "autopep8"

[[transformers]]
name = "rustfmt"