version = 1

[[analyzers]]
name = "secrets"

[[analyzers]]
name = "test-coverage"

[[analyzers]]
name = "sql"

[[analyzers]]
name = "scala"

[[analyzers]]
name = "java"

  [analyzers.meta]
  runtime_version = "12"

[[analyzers]]
name = "python"

  [analyzers.meta]
  runtime_version = "3.x.x"

[[analyzers]]
name = "csharp"

[[analyzers]]
name = "go"

  [analyzers.meta]
  import_root = "github.com/Ne-ku12/github-slideshow"
  dependencies_vendored = true

[[analyzers]]
name = "shell"

[[analyzers]]
name = "ruby"

[[transformers]]
name = "rubocop"

[[transformers]]
name = "standardrb"

[[transformers]]
name = "gofmt"

[[transformers]]
name = "gofumpt"

[[transformers]]
name = "dotnet-format"

[[transformers]]
name = "black"

[[transformers]]
name = "autopep8"

[[transformers]]
name = "isort"

[[transformers]]
name = "yapf"

[[transformers]]
name = "scalafmt"